enabled: true

namespace:
  create: true
  name: "runners"

crd:
  group: "azdo.stable.example.com"
  version: v1

serviceAccount:
  create: true
  annotations: {}

linux:
  enabled: true
  name: "bahri-linux-agent"
  type: "linux"
  pool: "linux"
  prefix: "lin-agent"
  image:
    repository: bahrinipun
    name: linux-dockeragent
    tag: latest
  resources:
    #  limits:
    #    cpu: 100m
    #    memory: 90Mi
    requests:
      cpu: 100m
      memory: 100Mi

  # hashicorpVault:
  #   oarid: ""
  #   env: "dev"
  #   serviceAccountName: vault-consumer
  #   agentInjectSecretConfig: "adpt/ado/agents/runner/linux"
  #   aksName: ""

  nodeSelector: {}

  tolerations: {}

  podAnnotations: {}

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000